package com.redhat.prudential_poc.pojo;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("既有保單")
public class Policy implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "ID")
	private java.lang.String id;
	@org.kie.api.definition.type.Label(value = "姓名")
	private java.lang.String name;
	@org.kie.api.definition.type.Label(value = "保單總額")
	private java.lang.Integer amount;

	public Policy() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Integer getAmount() {
		return this.amount;
	}

	public void setAmount(java.lang.Integer amount) {
		this.amount = amount;
	}

	public Policy(java.lang.String id, java.lang.String name,
			java.lang.Integer amount) {
		this.id = id;
		this.name = name;
		this.amount = amount;
	}

}