package com.redhat.prudential_poc.com.redhat.prudential_poc.pojo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Application implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Application() {
    }




}